scrapper:
  Card Captor Sakura:
    "Weiss Schwarz English": https://en.ws-tcg.com/cardlist/list/


  "Re:Zero":
    # JKTCG: http://jktcg.com/EN-RZ-S46/
    Yuyutei: https://yuyu-tei.jp/game_ws/sell/sell_price.php?ver=fsubw2.0


